### ISSUE TITLE
Contributing guidelines show invalid URL

### ISSUE THREAD

**Issue by holdenweb** [Trax-air/swagger-aggregator#7]
The guide at https://github.com/Trax-air/swagger-aggregator/blob/master/CONTRIBUTING.rst directs the reader to "Report bugs at https://github.com/cyprieng/swagger_aggregator/issues", which gives a 404 response. I presume this means ownership of the project changed at some point?

**Comment by cyprieng** [comment]
I just fixed it, thanks
